spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initial-size: 1
    min-idle: 20
mybatis:
  mapper-locations: classpath:mappers/*mapper.xml
  type-aliases-package: com.zzx.shiro.beans
